addiing cpp and header files of my elections project
woodooi/elections pull request #1
Opened 2022-11-30 23:30 UTC by woodooi

2022-12-21 20:11 UTC, ViktorYasin requested changes

2022-12-21 20:11 UTC, ViktorYasin commented on main.cpp
> +#include <C:\Users\Master\source\repos\Candidates\Candidates\classCandidates.h>
The link was incorrectly reset

2022-12-21 20:11 UTC, ViktorYasin commented on classCandidates.h
> +	void bubblesort(Candidate candidates[])
Incorrect function name

2022-12-22 13:46 UTC, ViktorYasin approved these changes

2023-02-23 21:03 UTC, zveres-ss requested changes

2023-02-23 21:03 UTC, zveres-ss commented on classCandidates.h
> +	void bubble_sort(Candidate candidates[])
bubble_sort
but
outWinner
getVotes

which style is final?

2023-02-23 21:03 UTC, zveres-ss commented on classCandidates.h
> +		bubblesort(candidates);
you changed method name to bubble_sort, code will not compile

2023-03-09 17:18 UTC, merged